# typed: false
# frozen_string_literal: true

# This file is auto-generated by the release pipeline.
# Do not edit by hand — see packaging/homebrew/gorun.rb.tmpl in
# github.com/kfet/gorun.
class Gorun < Formula
  desc "Run Go without installing Go — on-demand, verified toolchain launcher"
  homepage "https://github.com/kfet/gorun"
  version "0.1.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/kfet/gorun/releases/download/v0.1.1/gorun-0.1.1-darwin-arm64.tar.gz"
      sha256 "8c5f83a4c0212a20989fca4dc5691e3e24c900cb98e174cd8167144a82d32d6f"
    end
    on_intel do
      url "https://github.com/kfet/gorun/releases/download/v0.1.1/gorun-0.1.1-darwin-amd64.tar.gz"
      sha256 "dcb20a9153a32c02e994412bc67c1de682034b24e51628a9338aa63cfb277be7"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/kfet/gorun/releases/download/v0.1.1/gorun-0.1.1-linux-arm64.tar.gz"
      sha256 "ab7c133a1bb0abd222aaf02a8ed834b6bf9971558df544f8303dc396db822f2c"
    end
    on_intel do
      url "https://github.com/kfet/gorun/releases/download/v0.1.1/gorun-0.1.1-linux-amd64.tar.gz"
      sha256 "86f73231977233d138573c634796820e3a0a66b726763ca9ddb136222a0360e4"
    end
  end

  def install
    bin.install "gorun"
  end

  test do
    assert_match "gorun", shell_output("#{bin}/gorun version 2>&1")
  end
end
