# typed: false
# frozen_string_literal: true

# This file is auto-generated by the release pipeline.
# Do not edit by hand — see packaging/homebrew/harb.rb.tmpl in
# github.com/kfet/harb.
class Harb < Formula
  desc "Self-hosted RSS server speaking the Google Reader API dialect"
  homepage "https://github.com/kfet/harb"
  version "0.20.5"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/kfet/harb/releases/download/v0.20.5/harb-0.20.5-darwin-arm64.tar.gz"
      sha256 "0c80fe5bd325cb172e842a324e83737af98e386339b81d026ace2d68f4df7a6c"
    end
    on_intel do
      url "https://github.com/kfet/harb/releases/download/v0.20.5/harb-0.20.5-darwin-amd64.tar.gz"
      sha256 "05449f02e64568ce8b6a745642e7f50083be99d917eb4513884c98aa02bbcf94"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/kfet/harb/releases/download/v0.20.5/harb-0.20.5-linux-arm64.tar.gz"
      sha256 "4b63b7bb629a4d9a4ebdd7dc96cd8c334d7ab29c67f360e282bf65633d356f94"
    end
    on_intel do
      url "https://github.com/kfet/harb/releases/download/v0.20.5/harb-0.20.5-linux-amd64.tar.gz"
      sha256 "3fc204c01a83e93b7b0b7cfe5a9d89c64e04a4416da5371ac38ac0ab19c596fe"
    end
  end

  def install
    bin.install "harb"
  end

  test do
    assert_match "harb", shell_output("#{bin}/harb version 2>&1")
  end
end
