# typed: false
# frozen_string_literal: true

# This file is auto-generated by the release pipeline.
# Do not edit by hand — see packaging/homebrew/harb.rb.tmpl in
# github.com/kfet/harb.
class Harb < Formula
  desc "Self-hosted RSS server speaking the Google Reader API dialect"
  homepage "https://github.com/kfet/harb"
  version "0.21.2"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/kfet/harb/releases/download/v0.21.2/harb-0.21.2-darwin-arm64.tar.gz"
      sha256 "807f804084c1dbda895ee0391b53f04f11b4bd68628a461c5c40a3333a3b87ee"
    end
    on_intel do
      url "https://github.com/kfet/harb/releases/download/v0.21.2/harb-0.21.2-darwin-amd64.tar.gz"
      sha256 "21b7273bcf4c0453cbd7c305fc1c036bb79205e0a8776a9359ba9d18f344e329"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/kfet/harb/releases/download/v0.21.2/harb-0.21.2-linux-arm64.tar.gz"
      sha256 "3af7b408b80543e17b9ed7671e4aa74b3ca32a4f27e89905e291d73925a52ebf"
    end
    on_intel do
      url "https://github.com/kfet/harb/releases/download/v0.21.2/harb-0.21.2-linux-amd64.tar.gz"
      sha256 "ac0b7e9789d98f77c4e1c33bea689cb039bcaf2fd8155c4967e2968a4071bea5"
    end
  end

  def install
    bin.install "harb"
  end

  test do
    assert_match "harb", shell_output("#{bin}/harb version 2>&1")
  end
end
