# typed: false
# frozen_string_literal: true

# This file is auto-generated by the release pipeline.
# Do not edit by hand — see packaging/homebrew/harb.rb.tmpl in
# github.com/kfet/harb.
class Harb < Formula
  desc "Self-hosted RSS server speaking the Google Reader API dialect"
  homepage "https://github.com/kfet/harb"
  version "0.20.2"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/kfet/harb/releases/download/v0.20.2/harb-0.20.2-darwin-arm64.tar.gz"
      sha256 "b6fdf5a12d38b9d0f9e1abf4473476259dfb82167623cc46fd7dce48a77fe772"
    end
    on_intel do
      url "https://github.com/kfet/harb/releases/download/v0.20.2/harb-0.20.2-darwin-amd64.tar.gz"
      sha256 "66d7380f1b27b0f33f601520ab7acc2ca70f5987ca77c08dc5b94a151796b4a8"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/kfet/harb/releases/download/v0.20.2/harb-0.20.2-linux-arm64.tar.gz"
      sha256 "8918054c83cbb33f018e23304dab3886023b60dfac9e9e9584419a2abb04f814"
    end
    on_intel do
      url "https://github.com/kfet/harb/releases/download/v0.20.2/harb-0.20.2-linux-amd64.tar.gz"
      sha256 "25e4a14ac5f8fc74f194c1c1659f0c313af1d3473bf680786a154afb60668b3c"
    end
  end

  def install
    bin.install "harb"
  end

  test do
    assert_match "harb", shell_output("#{bin}/harb version 2>&1")
  end
end
